name: characters_list_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  http: ^1.3.0
  internet_connection_checker_plus: ^2.7.1
  rxdart: ^0.28.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  hive_ce_generator: ^1.8.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  talker_bloc_logger: ^4.7.1
  talker_flutter: ^4.7.1
  talker_logger: ^4.7.1

flutter:
  uses-material-design: true
